version: '3.5'
services:
  comunidade:
    build: .
    restart: always
    hostname: comunidade
    env_file:
      - .env
    networks:
      - backend
      
networks:
  backend:
    external:
      name: cartografia-network