version: '3.5'
services:
  comunidade-dev:
    build: 
      context: .
      dockerfile: dev.Dockerfile
    volumes: 
      - .:/var/www/gateway
    restart: always
    hostname: comunidade
    env_file:
      - .env
    networks:
      - backend
      
networks:
  backend:
    external:
      name: cartografia-network